### ISSUE TITLE
Useful libraries

### ISSUE THREAD

**Issue by cipriancus** [arthurflor23/surface-crack-detection#1]
Hello,

I am trying in many ways to configure this project. Could you please tell me what version of python, tensorflow and keras did you use?

I tried with py 3.5, 2.7 and keras 2.2.4 and other versions for Tensorflow but I couldn't find the correct combination.

Thanks a lot!

**Comment by arthurflor23** [comment]
Hi!
Sorry the lack of requirements.txt file for this project.
I don't remember the exact versions, but it was Python 3+ and Keras 2.2.4

What error did you have?

**Comment by cipriancus** [comment]
Hi!

Thank you for quick response.

I am using Keras 2.2.4, tensorflow 2 and python 3.6.9
I followed your advices from article and code. I took every command from main.py.
For last 2 commands, about test and train I have this error:

`##################
Error loading: .\model\unet_cracktile_checkpoint.hdf5
Dataset: cracktile
module 'tensorflow' has no attribute 'get_default_graph'
DIP:	 cracktile
Arch:	 unet
##################`

should I generate somehow hdf5 file?
I like your project and I want to work it.

Thanks a lot!

**Comment by arthurflor23** [comment]
Thanks for your interest!

About the error, I think its the keras version with the tensorflow version..
When this project  was created, keras used TF 1.x
So, you can try 2 ways

1. using keras 2.3.1 (support TF 2) with the TF 2 (here I don't know if keras will be compatible with the project code, however you will use both recent versions)
2. or, using keras 2.2.4 with the TF 1.x

Let me know if this helped you, or we can think another approach

**Comment by cipriancus** [comment]
Hey, thanks for the answer, have you run this code with Linux? 
I ran it in windows and I think there is the problem.

**Comment by arthurflor23** [comment]
Yes, it was (arch linux specifically)
In other projects mine, people have problem using windows, but with this error ``'tensorflow' has no attribute 'get_default_graph'`` I don't know.. did you try another approach?

**Comment by cipriancus** [comment]
Hey! I fixed the problem, it was windows, on ubuntu it works 👍  for anybody who is interested, if they have a Pickle error and some threading problems you have to switch to ubuntu, thank you!
